### ISSUE TITLE
Acronyms in app

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#106]
Acronyms are being picked up as hyperlinks in the app.

![image](https://user-images.githubusercontent.com/89025704/145033698-47bd5acb-2eee-4c67-8c82-736577889061.png)

**Comment by payeisa** [comment]
Not sure if [ #155](https://github.com/StatCan/StatCanPublication/issues/155) was supposed to fix content that has already been published. Will validate tomorrow after 8:30 a.m. The article "Survey of the Canada Emergency Business Account, first quarter 2021" contains acronyms.

**Comment by payeisa** [comment]
We will need to fix how acronyms are displaying. I understand we removed the functionality, but right now it they still look like hyperlinks (i.e. underlined). Naturally, acronyms should not be underlined.

You can refer to the article "Survey of the Canada Emergency Business Account" (published Dec 22) as an example.

**Comment by Jiandong-Guo** [comment]
This one was fixed couple of release ago, may relate to a different ticket. Please test in next release

**Comment by payeisa** [comment]
Tested and issue remains. Acronyms should not be underlined in the app.

![image](https://user-images.githubusercontent.com/89025704/149684669-1b820c29-f51c-43a9-ae3c-8c14f95559c2.png)

**Comment by payeisa** [comment]
On my tablet, when I click on an acronym, I am brought to the top of the article page. For example, if I click on ESGIS in the article "Enquête sociale générale - Identité sociale, 2020...), I am go to the top of the screen.
This behaviour does not happen on my phone.

**Comment by Pharste** [comment]
On my iPhone and iPad, nothing happens when I click on the acronyms. (They are still showing as hyperlinks)

**Comment by goodyke** [comment]
I verified the latest example given by @payeisa in this ticket (to ensure the problem was not with the content and not with the api).  It is not... this is something that needs to be fixed by the developers.
If you check the content you will see that FT-UCASS has been set up as an acronym (I will append a screenshot for this).  Then I checked the api and it is returning FT-UCASS as an acronym (not as a link).  Therefore, we need to display it as an acronym in the mobile app... @Jiandong-Guo if you have any concerns about this please reach out to me.

**Comment by goodyke** [comment]
@Jiandong-Guo below is the returned JSON for article 412 in alpha (I have highlighted the returned acronym in **bold**)

// 20220121132010
// https://sdr-daily-alpha.cloud.statcan.ca/o1/en/api/plus/article/412

{
  "id": "412",
  "title": "Data availability: Number and Salaries of Full-time Teaching Staff at Canadian Universities, 2020/2021",
  "url": "https://sdr-daily-alpha.cloud.statcan.ca/o1/en/plus/412-data-availability-number-and-salaries-full-time-teaching-staff-canadian-universities",
  "type": "Article",
  "published_date": "2021-12-23T08:31:40-0500",
  "summary": "",
  "subject_name": "Education, training and learning",
  "subject_id": "37",
  "new_data": false,
  "branding_image_src": "https://sdr-daily-alpha.cloud.statcan.ca/o1/sites/default/files/2021-12/university.jpg",
  "branding_image_alt": "University campus",
  "branding_image": "https://sdr-daily-alpha.cloud.statcan.ca/o1/sites/default/files/2021-12/university.jpg",
  "content": [
    "<div class=\"paragraph paragraph--type--layout paragraph--view-mode--full\">\n          \n      </div>",
    "<p>Data from the Full-time University and College Academic Staff System **(<abbr title=\"Full-time University and College Academic Staff System\"><a>FT-UCASS</a></abbr>)** survey for the 2020/2021 academic year are now available. Also available is the release \"<a href=\"https://www150.statcan.gc.ca/n1/daily-quotidien/211213/dq211213a-eng.htm\">Average time to Achieve Tenure Among University Academics in Canada: A National Overview</a>\" published in <em>The Daily</em> on December 13, 2021.</p>\n\n<p><a href=\"https://www150.statcan.gc.ca/n1/daily-quotidien/211220/dq211220f-eng.htm\" title=\"Data availability: Number and Salaries of Full-time Teaching Staff at Canadian Universities, 2020/2021\">Continue reading</a></p>",
    "<div class=\"paragraph paragraph--type--layout paragraph--view-mode--full\">\n          \n      </div>",
    "<section class=\"panel panel-info\"><header class=\"panel-heading\"><h2 class=\"panel-title\"> Contact information </h2></header>\n<div class=\"panel-body\">\n          \n            <div class=\"field field--name-field-highlight field--type-text-long field--label-hidden field--item\"><p>For more information, or to enquire about the concepts, methods or data quality of this release, contact us (toll-free 1-800-263-1136; 514-283-8300; <a href=\"mailto:infostats@statcan.gc.ca\">infostats@statcan.gc.ca</a>) or Media Relations (<a href=\"mailto:statcan.mediahotline-ligneinfomedias.statcan@statcan.gc.ca\">statcan.mediahotline-ligneinfomedias.statcan@statcan.gc.ca</a>).</p></div>\n      \n    </div></section>"
  ]
}

**Comment by goodyke** [comment]
Here is a screenshot of how it appears on the website.
![image](https://user-images.githubusercontent.com/88500621/150580728-3979d8be-25c9-4037-a607-75f317d91bf2.png)

**Comment by Jiandong-Guo** [comment]
I still use Kerry's sample  https://sdr-daily-alpha.cloud.statcan.ca/o1/en/api/plus/article/412
This api call will return 
![image](https://user-images.githubusercontent.com/58485300/150604690-74ae8d35-86ab-4eca-b73d-febe27c3f2ad.png)

put focus on last line:
 \u003Ca\u003EFT-UCASS\u003C\/a\u003E
the \u003C   ="<"
following by a
next is \u003E   =">"
following by FT-UCASS
next is \u003C="<"
following by \/a="/a"
and last is \u003E=">"
so this part will be html 
![image](https://user-images.githubusercontent.com/58485300/150605313-68531eb9-08e1-4749-9143-fbf0991c20f8.png)

so you can see it's a hyperlink even if there is no href is setup

**Comment by goodyke** [comment]
when I run the api the code that I see is:
<abbr title=\"Full-time University and College Academic Staff System\"><a>FT-UCASS</a></abbr>
This should signify an abbreviation... only the "<a href = " should signify a hyperlink.

**Comment by goodyke** [comment]
<abbr title="Full-time University and College Academic Staff System">FT-UCASS

This is a copy of the code above with GitHub formatting the HTML... it is not underlined.

**Comment by goodyke** [comment]
Here is the plain text with real hyperlinks:
"<section class=\"panel panel-info\"><header class=\"panel-heading\"><h2 class=\"panel-title\"> Contact information </h2></header>\n<div class=\"panel-body\">\n          \n            <div class=\"field field--name-field-highlight field--type-text-long field--label-hidden field--item\"><p>For more information, or to enquire about the concepts, methods or data quality of this release, contact us (toll-free 1-800-263-1136; 514-283-8300; <a href=\"mailto:infostats@statcan.gc.ca\">infostats@statcan.gc.ca</a>) or Media Relations (<a href=\"mailto:statcan.mediahotline-ligneinfomedias.statcan@statcan.gc.ca\">statcan.mediahotline-ligneinfomedias.statcan@statcan.gc.ca</a>).</p></div>\n      \n    </div></section>"

**Comment by goodyke** [comment]
And here is how GitHub formats the above text:
"<section class="panel panel-info"><header class="panel-heading"><h2 class="panel-title"> Contact information \n<div class="panel-body">\n \n <div class="field field--name-field-highlight field--type-text-long field--label-hidden field--item">

For more information, or to enquire about the concepts, methods or data quality of this release, contact us (toll-free 1-800-263-1136; 514-283-8300; <a href="mailto:infostats@statcan.gc.ca">infostats@statcan.gc.ca) or Media Relations (<a href="mailto:statcan.mediahotline-ligneinfomedias.statcan@statcan.gc.ca">statcan.mediahotline-ligneinfomedias.statcan@statcan.gc.ca).

\n \n "

**Comment by Jiandong-Guo** [comment]
I just follow the same pattern of #233, add a style to it(Github is a website, has its own header and global style, for us, we only have html content, it may not working for all the situation due to you don't know how many level parent tags this "a" tag locates).
the result:  see the abbreviation
   
![image](https://user-images.githubusercontent.com/58485300/150653332-1e2766a5-d13e-4e22-8d15-83fa5c94ab7c.png)

Please test it in next release

**Comment by goodyke** [comment]
@Jiandong-Guo I think the solution you implemented for this is the best that can be done for now (remove the underline which signifies a hyperlink).  However, I think we are going to need to learn how to parse an acronym tag of <abbr title> so that the full text can be shown (when a user clicks the abbreviation).

I will talk to Dave about this on Monday to see if my understanding is correct or not - and if he can help with the returned html code to make it easier for you.  Do you know how and abbreviation code should be given to you so that it displays correctly in mobile?

**Comment by Jiandong-Guo** [comment]
In web, when user move the mouse over(not click, just over) an abbreviation,  it will show the abbr tag's title attribute text. it's done by javascript, and this piece of javascript code may stay in header or dynamically generated during run time.  
In mobile, there is no mouse over and no finger over at all.  how to trigger it to show something even if api returns the abbr tag's title attribute text ?   only action is to tap that abbr or tap the abbr's child: hyperlink,   so the possible solution is ask api returns that piece of code inside the abbr(inine javascript), the problem is the app is using a piece of html content, no external library such as jQquery there, must be pure javascript. that will give api challenge.

**Comment by Rajat-Sen** [comment]
Validated. Thanks!
