### ISSUE TITLE
Icon on the launch screen

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#134]
The icon on the launch screen needs to be updated with the latest. Right now it's displaying the old one.

**Comment by Rajat-Sen** [comment]
Hi Forum, could you please make sure that we are using the latest logo on the launch screen.

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
I deleted my user profile, closed the app, but I still get the old icon:
![image](https://user-images.githubusercontent.com/89025704/146984917-48242585-70bd-4667-90c2-cebcaae8e618.png)

**Comment by ForumG-SC** [comment]
> I deleted my user profile, closed the app, but I still get the old icon:
> ![image](https://user-images.githubusercontent.com/89025704/146984917-48242585-70bd-4667-90c2-cebcaae8e618.png)

Can you clear cache of your device , delete the app, reboot device , reinstall app ?

**Comment by payeisa** [comment]
@ForumG-SC After uninstalling/reinstalling the app, I was able to validate this issue. It works as it should now and this ticket can be closed. Thanks, Isabelle
