### ISSUE TITLE
Publication screen (level-2) scroll bar

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#284]
Please move it to the side and make it consistent with level-1.

**Comment by zhuelle** [comment]
Controlled by the system and require to research to see if it is feasible.

**Comment by Jiandong-Guo** [comment]
Please test in next release to see if the change meets the requirement

**Comment by zhuelle** [comment]
@Jiandong-Guo Have you completed the work for this ticket? Or you completed the research of the ticket and added a Medium work effort on this ticket? Please confirm!

**Comment by Jiandong-Guo** [comment]
It's fixed in webview level, please do an internal test in next release

**Comment by Rajat-Sen** [comment]
It's not fixed properly as I cannot see the sidebar anymore!

**Comment by Rajat-Sen** [comment]
Still can't see

**Comment by zhuelle** [comment]
@Jiandong-Guo Rajat tested again and still cannot see the fix. Would you please check it and maybe it is a good idea to attach some pictures to show your fix in the ticket? Thanks!

**Comment by Jiandong-Guo** [comment]
@Rajat-Sen, It was roll back due to #381,will re-do it next week

**Comment by Jiandong-Guo** [comment]
@Rajat-Sen Please test it in next release

**Comment by Rajat-Sen** [comment]
Validated!
