### ISSUE TITLE
Remove space between three dots and menu items (second level publication)

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/StatcanPublicationUAT#369]
there should be no space from three dots and menu items. Please checkout the prototype for visual reference.
Link for prototype: https://xd.adobe.com/view/ba93d6fc-6df6-445a-b4c0-a31e8c15c6e1-efc0/screen/ac0fbd50-01cc-4f19-b0cf-884d21c53235

**Comment by giftydeep** [comment]
This is already fixed and was also the part of #338

**Comment by Rajat-Sen** [comment]
@giftydeep, It's not fixed properly yet! Please see the attached screenshot.

**Comment by Rajat-Sen** [comment]
![image](https://user-images.githubusercontent.com/38566088/171932405-2f5cfbd7-b453-4809-8263-932f1f791abc.jpeg)

**Comment by giftydeep** [comment]
@Rajat-Sen this is how it looked for me. Not sure why you seeing that space.
![IMG_1178](https://user-images.githubusercontent.com/8207028/171948546-ecad60fc-457e-4126-bf4f-e3a75a5e575b.jpg)

**Comment by Rajat-Sen** [comment]
@giftydeep, I am still seeing the space. Please double check on a bigger device. Thanks!

**Comment by giftydeep** [comment]
This ticket can be closed after we apply the fix for #338.

**Comment by giftydeep** [comment]
@zhuelle I am going to resolve this ticket and assign it to @Rajat-Sen for testing, Since we agreed to include #338 in this deployment.

**Comment by Rajat-Sen** [comment]
Not working! Please refer to the attached screenshot.

**Comment by Rajat-Sen** [comment]
![image](https://user-images.githubusercontent.com/38566088/185215049-155214ce-fffe-4a67-be70-b9384002f026.png)

**Comment by Jiandong-Guo** [comment]
still have space for tab
![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2022-09-28 at 16 26 53](https://user-images.githubusercontent.com/58485300/192882522-77df6d49-0a79-4160-8553-cfea1efff908.png)

**Comment by giftydeep** [comment]
@Jiandong-Guo The reason i can't work on this ticket is because I use 12 mini which has a small screen and it looks fine on that. I have attached the screenshot as well.  I don't have any bigger device or MacBook to test this. 

![Image](https://user-images.githubusercontent.com/8207028/192883960-7cb6a4dd-07fc-4a92-8058-4e696730a3e7.jpg)

**Comment by Jiandong-Guo** [comment]
@giftydeep Please use simulator, It has space in android emulator too.

**Comment by zhuelle** [comment]
This is not a priority now.

**Comment by weglmar** [comment]
@zhuelle Hi Ellen, could you please let me know what the estimated effort is?

**Comment by Pharste** [comment]
Confirming this is still an issue. Tested on iPad pro: 
![menu](https://github.com/StatCan/StatcanPublicationUAT/assets/89025880/f5d54d49-f0bd-4a72-a4f6-a446ed3fa39d)
