### ISSUE TITLE
StatsCAN (v1.0.10): Article level 2 text not centered

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#410]
Hello,
With the new release, the article level 2 screen has been modified.
The text carries over too far to the right and cuts off (see screenshot).

![image](https://user-images.githubusercontent.com/98898969/175313124-7c48f1ce-970c-4aca-8d04-669024addbd9.png)

Similar to issue reported in last release; https://github.com/StatCan/StatcanPublicationUAT/issues/381 

Testing on iPhone X, iOS 15.5.

FYI @Pharste @levegab @Rajat-Sen

**Comment by zhuelle** [comment]
@weglmar Please confirm if a new deployment is required to fix the issue before deploy it production. I would assume so but would like to get confirmation. Thanks!

**Comment by weglmar** [comment]
@zhuelle Yes, a deployment would be required before we deploy to Production. Thank you!

**Comment by Jiandong-Guo** [comment]
This issue happens for some articles in iOS side, and it is existing in old version too, will fix it in next release

**Comment by Jiandong-Guo** [comment]
![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2022-06-24 at 14 09 43](https://user-images.githubusercontent.com/58485300/175619849-86a914c0-94da-4313-bc1b-5a8f11e77c52.png)
![Simulator Screen Shot - iPhone 12 Pro - 2022-06-24 at 14 15 22](https://user-images.githubusercontent.com/58485300/175619916-cf1f9c88-57c3-4d40-aeea-3471357ee33a.png)

**Comment by zhuelle** [comment]
@Jiandong-Guo Do you mean this issue is existing in current Production version 1.0.6? I thought this issue is introduced in the new version 1.0.10. Please confirm!

**Comment by Jiandong-Guo** [comment]
Yes, It is a new issue related to content instead of styling. It was fixed and ready to test in next release

**Comment by ForumG-SC** [comment]
@weglmar Please update the app and test this ticket. Deployment has been completed. Thanks.

**Comment by weglmar** [comment]
The issue is still appearing on certain articles: 

![image](https://user-images.githubusercontent.com/98898969/176680889-dcba07bb-2a29-4ad3-ab15-f29a47fb6117.png)

![image](https://user-images.githubusercontent.com/98898969/176680919-8a5eb28d-daa1-4806-8b7f-9eb5c5537855.png)

**Comment by Jiandong-Guo** [comment]
@weglmar Please let me know your device name and ios version. 
I didn't find this issue  from iPad ios 12 and iphone 12 pro ios 15.4 simulator.

**Comment by Jiandong-Guo** [comment]
@weglmar Please test again after updating or uninstall/re-install. I want to hear your feedback before sending release email.
currently, the closest simulator to your device is iphoneX iOS 13.4, I tested on this one.  Have nice Canada day!

**Comment by weglmar** [comment]
@Jiandong-Guo sorry for not getting back sooner, I meant to before signing off on Thursday but got caught up with something. It looks good now! 
I hope you had a great and relaxing long weekend!! :)

**Comment by zhuelle** [comment]
@weglmar Hi Martyna, please close this ticket if the testing is good. I believe this is the ticket that blocker Production deployment. Once this is closed, the dev team can proceed production deployment. Thanks!
